name: main

on:
  # NOTE(djeeno): ref. https://docs.github.com/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # NOTE(djeeno): ref. https://docs.github.com/actions/reference/events-that-trigger-workflows#schedule
  schedule:
    - cron: '0 9 * * *'

env:
  REPOSITORY_PATH: src/github.com/djeeno/bqtableschema

jobs:
  ci:
    name: CI
    # NOTE(djeeno): https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.REPOSITORY_PATH }}

      # NOTE(djeeno): https://github.com/actions/setup-go#usage
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      # NOTE(djeeno): https://github.com/actions/cache/blob/main/examples.md#go---modules
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-

      # NOTE(djeeno): https://github.com/actions/cache#skipping-steps-based-on-cache-hit
      - name: Run go mod download if not cache hit
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          GO111MODULE: auto
        working-directory: ${{ env.REPOSITORY_PATH }}
        run: |
          go mod download

      # NOTE(djeeno): https://github.com/google-github-actions/setup-gcloud#usage
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}                        ## NOTE(djeeno): JSON の中の project_id に相当。 GitHub Actions のログに出ないようにするため
          service_account_email: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}  ## NOTE(djeeno): JSON の中の client_email に相当。 GitHub Actions のログに出ないようにするため
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  ## NOTE(djeeno): JSON の中身すべてに相当。
          export_default_credentials: true

      - name: Run make ci
        env:
          GO111MODULE: auto
        working-directory: ${{ env.REPOSITORY_PATH }}
        run: |
          make ci

      # NOTE(djeeno): https://github.com/actions/upload-artifact#usage
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: coverage.html
      #    path: ${{ env.REPOSITORY_PATH }}/coverage.html

      # NOTE(djeeno): https://github.com/codecov/codecov-action#example-workflowyml-with-codecov-action
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ env.REPOSITORY_PATH }}
